import mongoose, { Schema, Document } from 'mongoose';

export interface IScreeningResult extends Document {
  applicantId: mongoose.Types.ObjectId;
  jobId: mongoose.Types.ObjectId;
  matchScore: number; // 0-100 indicating percentage match
  strengths: string[]; // Key reasons why they match
  gaps: string[]; // Missing requirements or experience
  recommendation: 'Strong Hire' | 'Hire' | 'Consider' | 'Reject';
  explanationDetails: string; // The verbatim natural-language explanation generated by Gemini
  screenedAt: Date;
}

const ScreeningResultSchema: Schema = new Schema({
  applicantId: { type: Schema.Types.ObjectId, ref: 'Applicant', required: true },
  jobId: { type: Schema.Types.ObjectId, ref: 'Job', required: true },
  matchScore: { type: Number, required: true, min: 0, max: 100 },
  strengths: { type: [String], required: true, default: [] },
  gaps: { type: [String], required: true, default: [] },
  recommendation: { 
    type: String, 
    enum: ['Strong Hire', 'Hire', 'Consider', 'Reject'], 
    required: true 
  },
  explanationDetails: { type: String, required: true },
  screenedAt: { type: Date, default: Date.now },
});

export default mongoose.model<IScreeningResult>('ScreeningResult', ScreeningResultSchema);
